"""initial schema

Revision ID: 46567a99f6e9
Revises: 
Create Date: 2026-08-25 23:17:23.801459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46567a99f6e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'open', 'closed', name='term_status', native_enum=False, length=20), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_term')),
    sa.UniqueConstraint('year', 'semester', name='uq_academic_term_year_semester')
    )
    with op.batch_alter_table('academic_term', schema=None) as batch_op:
        batch_op.create_index('uq_academic_term_single_current', ['is_current'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))

    op.create_table('class_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_group')),
    sa.UniqueConstraint('curriculum', 'level', 'section', name='uq_class_group_identity')
    )
    op.create_table('criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_criterion'))
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject')),
    sa.UniqueConstraint('code', name=op.f('uq_subject_code'))
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'faculty', 'student', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('school_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('legacy_md5', sa.String(length=32), nullable=True),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role <> 'student' OR class_group_id IS NOT NULL", name=op.f('ck_account_student_requires_class')),
    sa.CheckConstraint('password_hash IS NOT NULL OR legacy_md5 IS NOT NULL', name=op.f('ck_account_some_credential_present')),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], name=op.f('fk_account_class_group_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('email', name=op.f('uq_account_email')),
    sa.UniqueConstraint('school_id', name=op.f('uq_account_school_id'))
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_class_group_id'), ['class_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_role'), ['role'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], name=op.f('fk_question_criterion_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_question_term_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index('ix_question_term_criterion', ['term_id', 'criterion_id', 'position'], unique=False)

    op.create_table('teaching_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], name=op.f('fk_teaching_assignment_class_group_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['account.id'], name=op.f('fk_teaching_assignment_faculty_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_teaching_assignment_subject_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_teaching_assignment_term_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_assignment')),
    sa.UniqueConstraint('term_id', 'faculty_id', 'class_group_id', 'subject_id', name='uq_teaching_assignment_identity')
    )
    with op.batch_alter_table('teaching_assignment', schema=None) as batch_op:
        batch_op.create_index('ix_teaching_assignment_lookup', ['term_id', 'class_group_id'], unique=False)

    op.create_table('evaluation_response',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['teaching_assignment.id'], name=op.f('fk_evaluation_response_assignment_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_evaluation_response_term_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_response'))
    )
    with op.batch_alter_table('evaluation_response', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_response_report', ['term_id', 'assignment_id'], unique=False)

    op.create_table('evaluation_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['teaching_assignment.id'], name=op.f('fk_evaluation_submission_assignment_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], name=op.f('fk_evaluation_submission_student_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_evaluation_submission_term_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_submission')),
    sa.UniqueConstraint('term_id', 'student_id', 'assignment_id', name='uq_evaluation_submission_once')
    )
    with op.batch_alter_table('evaluation_submission', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_submission_rate', ['term_id', 'assignment_id'], unique=False)

    op.create_table('evaluation_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_evaluation_rating_rating_in_range')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_evaluation_rating_question_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['response_id'], ['evaluation_response.id'], name=op.f('fk_evaluation_rating_response_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_rating')),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_evaluation_rating_once')
    )
    with op.batch_alter_table('evaluation_rating', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_rating_question', ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_rating', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_rating_question')

    op.drop_table('evaluation_rating')
    with op.batch_alter_table('evaluation_submission', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_submission_rate')

    op.drop_table('evaluation_submission')
    with op.batch_alter_table('evaluation_response', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_response_report')

    op.drop_table('evaluation_response')
    with op.batch_alter_table('teaching_assignment', schema=None) as batch_op:
        batch_op.drop_index('ix_teaching_assignment_lookup')

    op.drop_table('teaching_assignment')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_term_criterion')

    op.drop_table('question')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_role'))
        batch_op.drop_index(batch_op.f('ix_account_class_group_id'))

    op.drop_table('account')
    op.drop_table('subject')
    op.drop_table('criterion')
    op.drop_table('class_group')
    with op.batch_alter_table('academic_term', schema=None) as batch_op:
        batch_op.drop_index('uq_academic_term_single_current', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))

    op.drop_table('academic_term')
    # ### end Alembic commands ###
