"""audit log

Revision ID: b3ba61084771
Revises: fa1ab8b7f809
Create Date: 2026-08-26 12:53:00.321745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ba61084771'
down_revision: Union[str, None] = 'fa1ab8b7f809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['account.id'], name=op.f('fk_audit_event_actor_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_at', ['at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_at')

    op.drop_table('audit_event')
    # ### end Alembic commands ###
