"""reminder log

Revision ID: b556a58e9a94
Revises: 46567a99f6e9
Create Date: 2026-08-26 11:06:32.386805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b556a58e9a94'
down_revision: Union[str, None] = '46567a99f6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_reminder_log_account_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_reminder_log_term_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_log'))
    )
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_log_lookup', ['term_id', 'account_id', 'sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_log_lookup')

    op.drop_table('reminder_log')
    # ### end Alembic commands ###
