"""mid-term pulse

Revision ID: fa1ab8b7f809
Revises: ad374ac06066
Create Date: 2026-08-26 12:08:23.551332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1ab8b7f809'
down_revision: Union[str, None] = 'ad374ac06066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['teaching_assignment.id'], name=op.f('fk_pulse_round_assignment_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pulse_round'))
    )
    with op.batch_alter_table('pulse_round', schema=None) as batch_op:
        batch_op.create_index('ix_pulse_round_assignment', ['assignment_id'], unique=False)

    op.create_table('pulse_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['pulse_round.id'], name=op.f('fk_pulse_participation_round_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], name=op.f('fk_pulse_participation_student_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pulse_participation')),
    sa.UniqueConstraint('round_id', 'student_id', name='uq_pulse_once')
    )
    op.create_table('pulse_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('pace', sa.SmallInteger(), nullable=False),
    sa.Column('clarity', sa.SmallInteger(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['pulse_round.id'], name=op.f('fk_pulse_reply_round_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pulse_reply'))
    )
    with op.batch_alter_table('pulse_reply', schema=None) as batch_op:
        batch_op.create_index('ix_pulse_reply_round', ['round_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulse_reply', schema=None) as batch_op:
        batch_op.drop_index('ix_pulse_reply_round')

    op.drop_table('pulse_reply')
    op.drop_table('pulse_participation')
    with op.batch_alter_table('pulse_round', schema=None) as batch_op:
        batch_op.drop_index('ix_pulse_round_assignment')

    op.drop_table('pulse_round')
    # ### end Alembic commands ###
